server:
  port: 8084
spring:
  application:
    name: micro-credit-card
  spring:
    data:
      mongodb:
        host: localhost
        port: 27017
        database: mibankdb

eureka:
  client:
    fetch-registry: 'true'
    enable: 'true'
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://localhost:8761/eureka

