server:
  port: 8080

spring:
  application:
    name: autenticacion
  data:
    mongodb:
      uri: mongodb+srv://adminMongo:Admin123*@cluster0.p6zu4mw.mongodb.net/mibankdb
      database: mibankdb
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration

  main:
      allow-circular-references: true
jwt:
  secret: secret

admin-paths:
  paths:
    - uri: "/api/customers/createCustomer"
      method: "POST"
    - uri: "/api/accounts"
      method: "PUT"
    - uri: "/api/customers/{1}[a-zA-Z0-9]+"
      method: "GET"
    - uri: "/api/customers/{customerId}[a-zA-Z0-9]+/accounts"
      method: "GET"


eureka:
  client:
    service-url:
      defaultZone: http://serviceDiscovery:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
