server:
  port: 8085
spring:
  application:
    name: micro-customer-account
  spring:
    data:
      mongodb:
        uri: mongodb+srv://adminMongo:Admin123*@p6zu4mw.mongodb.net/mibankdb

eureka:
  client:
    fetch-registry: 'true'
    enable: 'true'
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://localhost:8761/eureka

